version: '3.9'

services:
    db:
        image: postgres:15.6-alpine3.19
        restart: unless-stopped
        ports:
            - '5433:5432'
        environment:
            POSTGRES_DB: django_kubernetes
            POSTGRES_USER: django_kubernetes
            POSTGRES_PASSWORD: django_kubernetes
        volumes:
            - postgres-data:/var/lib/postgresql/data
    app:
        build: .
        restart: unless-stopped
        ports:
            - '8000:8000'
        depends_on: db
        environment:
            - CORESETTINGS_DATABASES: '{default:{"HOST":"db"}}'
            - CORESETTINGS_LOCAL_SETTINGS_PATH: 'local/settings.prod.py'
volumes:
    postgres-data:
        driver: local
